version: '3.5'

networks:
  tiny-tiktok_net:
    driver: bridge

services: 
 tiny-tiktok:
  build:
   context: .
   dockerfile: ./modd.DockerFile
  container_name: tiny-tiktok
  environment:
   TZ: Asia/Shanghai
   GOPROXY: https://goproxy.cn,direct
  working_dir: /tiny-tiktok
  volumes:
   - .:/go/tiny-tiktok
  privileged: true
  restart: always
  networks:
   - tiny-tiktok_net
  ports:
   - "8888:8888"
   - "8080:8080"
   - "8081:8081"
   - "8082:8082"
   - "8083:8083"
   - "8084:8084"
   - "8085:8085"
   - "8086:8086"
  depends_on:
   - etcd
   - redis

 etcd:
  image: bitnami/etcd:latest
  environment: 
   - TZ=Asia/Shanghai
   - ALLOW_NONE_AUTHENTICATION=yes
   - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
  ports: 
   - "2379:2379"

  # Redis
 redis:
  image: redis:7.0.12
  ports:
   - 6379:6379
  # volumes:
  #  - ./pkg/configs/redis/redis.conf:/etc/redis/redis.conf
  # command: "redis-server /etc/redis/redis.conf"