Name: service
Host: 0.0.0.0
Port: 8888
MaxBytes: 33554432
Timeout: 30000 # 30s

Auth:
  AccessSecret: "AccessSecret"
  AccessExpire: 604800

Cos:
  URL:	"https://tiny-tiktok-1320230835.cos.ap-beijing.myqcloud.com"
  SecretID:  "AKIDoUyGPNBcGoAPajgXM6kMo9SdihU8gATX"
  SecretKey: "uoX9mDVhmldMySq7GQUfkhZGrMk9Rbgf"

RedisConf:
  Host: "127.0.0.1:6379"
  Type: "node"
  Pass: ""
  Tls:  false
  DB:   0

LogConf:
  ServiceName: "api_gateway"
  Mode: "file"
  Path: "api_gateway/logs"

#rpc service
FeedRpcConf:
  Etcd:
    Hosts:
      - etcd:2379
    Key: feed.rpc


UserRpcConf:
  Etcd:
    Hosts:
      - etcd:2379
    Key: user.rpc
  NonBlock: true

  
PublishRpcConf:
  Etcd:
    Hosts:
      - etcd:2379
    Key: publish.rpc

CommentRpcConf:
  Etcd:
    Hosts:
      - etcd:2379
    Key: comment.rpc
    
FavoriteRpcConf:
  Etcd:
    Hosts:
      - etcd:2379
    Key: favorite.rpc
